title: "[Idea] "
body:
  - type: markdown
    attributes:
      value: |
        Use this category to propose new ideas or improvements.
        For confirmed bugs, use the Bug Report issue form instead.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve? Who is affected?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired behavior/API/UX and constraints.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: risks
    attributes:
      label: Risks / compatibility / security considerations
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched for existing similar ideas.
          required: true
